<img src="images/usm.png" width="480" height="240" align="left"/>

# MAT281 - 2° Semestre 2019
## Aplicaciones de la Matemática en la Ingeniería

EL siguiente laboratorio debe realizarse de manera individual. No es posible copiar y pegar código de otros estudiantes. 
Pueden consultar internet (stackoverflow, por ejemplo), pero deben indicar sus fuentes cuando corresponda.

**Nombre**: *Juan Fco. Briceño Figueroa*

**Rol**: *201510522-7*



## Objetivos del laboratorio

* Reforzar conceptos básicos de la librería numpy.


## Contenidos

* [Problema 01](#p1)
* [Problema 02](#p2)
* [Problema 03](#p3)

<a id='p1'></a>
## I.- Problema 01

Los **peaks**  son puntos rodeados por valores más pequeños en ambos lados. Por ejemplo:

* Para el arreglo unidimensional $a$ = [1, 3, 7, 1, 2, 6, 0, 1], los valores máximos son el 7 y 6, cuyas posiciones corresponden al lugar 3 y 6, respectivamente.


Implemente una función llamada `findPeaks` cuyo input sea un arreglo unidimensional y cuyo ouput retorne el valor del (o los) peaks.

* **Ejemplo**: *findPeaks(a)* = $(7,6)$

In [7]:
import numpy as np

def findPeaks(lista):
    Indices_maximo =[]
    i=1
    while i < len(lista)-1: #genera un ciclo while para poder iterar por las casillas intermedias 
            if lista[i] > lista[i+1] and lista[i] > lista[i-1]: #compara con los valores colindantes
                Indices_maximo.append(i) #agrega los indices a nuestra lista
            i=i+1
        
    Extremos=[]
    for i in Indices_maximo:
        Extremos.append(lista[i]) #busca los valores en las posiciones entregadas por Indices_maximo
    return Extremos

#pruebas
np.random.seed(16)
lista_p=np.random.randint(0,12,size=9)
lista_p2=[1, 3, 7, 1, 2, 6, 0, 1]
print(lista_p)
print(findPeaks(lista_p))


[ 9  9  5  1 11  4  4  9  0]
[11, 9]


<a id='p2'></a>
## II.- Problema 02

La función **strides($a,n,p$)**, corresponde a transformar un arreglo unidimensional $a$ en una matriz de $n$ columnas, en el cual las filas se van construyendo desfasando la posición del arreglo en $p$ pasos hacia adelante.

* Para el arreglo unidimensional $a$ = [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], la función strides($a,4,2$), corresponde a crear una matriz de $4$ columnas, cuyos desfaces hacia adelante se hacen de dos en dos. 

El resultado tendría que ser algo así:$$\begin{pmatrix}
 1& 2 &3 &4 \\ 
 3&  4&5&6 \\ 
 5& 6 &7 &8 \\ 
 7& 8 &9 &10 \\ 
\end{pmatrix}$$


Implemente una función llamada `strides(a,4,2)` cuyo input sea un arreglo unidimensional y retorne la matriz de $4$ columnas, cuyos desfaces hacia adelante se hacen de dos en dos. 

* **Ejemplo**: *strides($a$,4,2)* =$\begin{pmatrix}
 1& 2 &3 &4 \\ 
 3&  4&5&6 \\ 
 5& 6 &7 &8 \\ 
 7& 8 &9 &10 \\ 
\end{pmatrix}$


In [7]:
import numpy as np


def strides(lista): #prueba 2
    c_p=0
    c_n=0
    matriz_list=[]
    list_aux = []
    i=0
    while i<len(lista):
        if c_n<4:
            list_aux.append(lista[i])
            c_n+=1
            i+=1
        else:
            c_p+=2 #corre los espacios para cada iteracion 
            matriz_list.append(list(list_aux))
            i=c_p
            c_n=0
            del(list_aux[:])
            continue
    matriz_list.append(list(list_aux)) #solucion para incluir el ultimo
    return np.array(matriz_list)

#pruebas

lista_p=[ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(strides(lista_p))


[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 5  6  7  8]
 [ 7  8  9 10]]


<a id='p3'></a>
## III.- Problema 03


Un **cuadrado mágico** es una matriz de tamaño $n \times n$ de números enteros positivos tal que 
la suma de los números por columnas, filas y diagonales principales sea la misma. Usualmente, los números empleados para rellenar las casillas son consecutivos, de 1 a $n^2$, siendo $n$ el número de columnas y filas del cuadrado mágico.

Por ejemplo, 

* $A= \begin{pmatrix}
 4& 9 &2 \\ 
 3&  5&7 \\ 
 8& 1 &6 
\end{pmatrix}$,
es un cuadrado mágico.

* $B= \begin{pmatrix}
 4& 2 &9 \\ 
 3&  5&7 \\ 
 8& 1 &6 
\end{pmatrix}$, no es un cuadrado mágico.

Implemente una función llamada `es_cudrado_magico` cuyo input sea una matriz cuadrada y cuyo ouput retorne *True* si es un cuadrado mágico o 'False', en caso contrario

* **Ejemplo**: *es_cudrado_magico($A$)* = True, *es_cudrado_magico($B$)* = False


In [1]:
def es_cuadrado_magico(A):
    n = A.shape[0]
    eje_x=np.sum(A, axis=0)
    eje_y=np.sum(A, axis=1)
    diagonal = np.trace(A)
    anti_diagonal = np.trace(np.fliplr(A)) #calcula la diago
    if np.array_equal(eje_x,eje_y) and (eje_x==diagonal).all  and np.array_equal(diagonal,anti_diagonal):
        return True
    else:
        return False

#prueba
A = np.array([[4,9,2],[3,5,7],[8,1,6]])
print(es_cuadrado_magico(A))

B = np.array([[4,2,9],[3,5,7],[8,1,6]])
print(es_cuadrado_magico(B))

NameError: name 'np' is not defined